-- INTRANET 부터 생성할것!!

CREATE TABLE MEMBER(
    MNO NUMBER PRIMARY KEY,           --회원번호
    USERID VARCHAR2(50) NOT NULL UNIQUE, --회원 아이디
    USERPWD VARCHAR2(300) NOT NULL, -- 비밀번호
    USERNAME VARCHAR2(15) NOT NULL, -- 회원이름
    GENDER CHAR(1) CHECK (GENDER IN('M','F')),  --성별
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,     --이메일
    PHONE VARCHAR2(50) UNIQUE NOT NULL,     --전화번호
    ADDRESS VARCHAR2(300) NOT NULL,         --주소
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL,--등록일
    CNO NUMBER,                      --자녀 번호
    CNAME VARCHAR2(20),						-- 자녀 이름
    CBDATE DATE,                    -- 자녀 생일
    CGENDER CHAR(1) CHECK (CGENDER IN ('M','F')),                    -- 자녀 성별
    CCLASS NUMBER CHECK (CCLASS IN (1,2,3,4)),                          -- 자녀 반
    MSTATUS VARCHAR2(1) DEFAULT 'N' CHECK (MSTATUS IN('Y','N')), -- 회원상태 Y- 가입상태 N- 삭제상태
    JOB_CODE NUMBER                                             -- 아이디 정보 확인
);


CREATE TABLE BOARDTYPE(
    BTYPE NUMBER PRIMARY KEY,
    BNAME VARCHAR2(20) NOT NULL UNIQUE
);


INSERT INTO BOARDTYPE VALUES(1,'공지사항');
INSERT INTO BOARDTYPE VALUES(2,'앨범');
INSERT INTO BOARDTYPE VALUES(3,'문의보내기');


CREATE TABLE BOARD(
    BNO NUMBER PRIMARY KEY,                     -- 게시판번호
    BTITLE VARCHAR2(300) NOT NULL,              -- 게시판제목
    BCONTENT VARCHAR2(3000) NOT NULL,           -- 게시판 내용
    BWRITER VARCHAR2(50),                       -- 게시판 작성자
    BCOUNT NUMBER,                              -- 조회수
    BDATE DATE DEFAULT SYSDATE,                 -- 작성날짜
    QDATE DATE,                                 -- 상담 날짜
    BTYPE NUMBER,                               -- 게시판 타입(공지사항, 앨범, QNA)
    BFILE VARCHAR2(300),                         -- 첨부파일 or 사진
    BSTATUS VARCHAR2(1) DEFAULT 'Y' CHECK (BSTATUS IN('Y','N')),-- 게시글 삭제 상태(Y-삭제안됨 N-삭제됨)
    QSTATUS VARCHAR2(1) DEFAULT 'N' CHECK (QSTATUS IN('Y','N')), -- 문의 확인 상태
    CONSTRAINT BOARD_TYPE FOREIGN KEY(BTYPE) REFERENCES BOARDTYPE(BTYPE)
);

CREATE TABLE GBOARD( -- 사진게시판
    GNO NUMBER PRIMARY KEY,                                     --게시판번호
    GTITLE VARCHAR2(300) NOT NULL,                              --제목
    GCONTENT VARCHAR2(3000) NOT NULL,                           --내용
    GwRITER VARCHAR2(50),                                       --작성자
    GCOUNT NUMBER,                                              --조회수
    GDATE DATE DEFAULT SYSDATE,                                 --작성날짜
    GFILE VARCHAR2(300),                                        --첨부파일
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y','N'))    --게시글 삭제 상태
);

CREATE TABLE QNA(
    QNO NUMBER PRIMARY KEY,                                     --문의 번호
    QTITLE VARCHAR2(300) NOT NULL,                              --문의 제목
    QCONTENT VARCHAR2(3000) NOT NULL,                           --문의 내용
    QWRITER VARCHAR2(50),                                       --작성자
    QDATE DATE DEFAULT SYSDATE,                                 --문의작성날짜
    ASK_DATE DATE,                                              --문의 신청 날짜
    CHK_STATUS VARCHAR2(1) DEFAULT 'N' CHECK (CHK_STATUS IN('Y','N')) -- 문의 확인여부
);
INSERT INTO QNA VALUES(SEQ_QNA.NEXTVAL,'상담신청합니다.','종일반 문제로 상담신청 합니다.','dalmom',DEFAULT,2020/03/12,DEFAULT);
INSERT INTO QNA VALUES(SEQ_QNA.NEXTVAL,'상담 하려고합니다...','민정이 동생 대기걸어놓으려고 하는데 서류 지침해야하나요?','minzzang',DEFAULT,2020/03/27,DEFAULT);
INSERT INTO QNA VALUES(SEQ_QNA.NEXTVAL,'선생님.. 상담이요~^^','달이장난감을 친구가 가져갔다고 하네요..ㅠㅠ 잠시 이야기 나누고 싶은데 문자 남겨주세요..','dalmom',DEFAULT,2020/03/16,DEFAULT);

CREATE TABLE ALIMCODE(
    ALIM_CODE NUMBER PRIMARY KEY,           -- 알림장 구별번호
    ALIM_NAME VARCHAR2(20)                  -- 알림장 이름
);

INSERT INTO ALIMCODE VALUES(1,'아이 알림장');
INSERT INTO ALIMCODE VALUES(2,'귀가 통지서');
INSERT INTO ALIMCODE VALUES(3,'투약 통지서');

CREATE TABLE ALIMNOTE(
    AL_NO NUMBER PRIMARY KEY,       -- 알림장번호
    AL_CODE NUMBER,       -- 알림장 구별번호
    CNO NUMBER,                  -- 자녀번호
    AL_CONTENT VARCHAR2(1000),      -- 알림장내용
    AL_FEEL VARCHAR2(20),           -- 기분
    AL_HEATH VARCHAR2(20),          -- 건강
    AL_TEMP VARCHAR2(20),           -- 체온
    AL_MEAL VARCHAR2(20),           -- 식사여부
    AL_SLEEP VARCHAR2(20),          -- 수면시간
    AL_POOP VARCHAR2(20),           -- 배변상태
    AL_WRITER VARCHAR2(50),         -- 작성자
    AL_DATE DATE DEFAULT SYSDATE,					-- 작성날짜
    ALIM_CK VARCHAR2(10),			-- 알림체크
    CONSTRAINT AL_CNO FOREIGN KEY(CNO) REFERENCES CHILD(CHILD_CODE),
    CONSTRAINT AL_WRITER FOREIGN KEY(AL_WRITER) REFERENCES MEMBER(USERID),
    CONSTRAINT AL_CODE FOREIGN KEY(AL_CODE) REFERENCES ALIMCODE(ALIM_CODE)
);
COMMENT ON COLUMN ALIMNOTE.AL_NO IS '글번호';
COMMENT ON COLUMN ALIMNOTE.AL_CODE IS '알림코드';
COMMENT ON COLUMN ALIMNOTE.CNO IS '원아번호';
COMMENT ON COLUMN ALIMNOTE.AL_CONTENT IS '상세내용';
COMMENT ON COLUMN ALIMNOTE.AL_FEEL IS '기분';
COMMENT ON COLUMN ALIMNOTE.AL_HEALTH IS '건강';
COMMENT ON COLUMN ALIMNOTE.AL_TEMP IS '체온';
COMMENT ON COLUMN ALIMNOTE.AL_MEAL IS '식사';
COMMENT ON COLUMN ALIMNOTE.AL_SLEEP IS '수면';
COMMENT ON COLUMN ALIMNOTE.AL_POOP IS '배변';
COMMENT ON COLUMN ALIMNOTE.AL_WRITER IS '작성자';
COMMENT ON COLUMN ALIMNOTE.AL_DATE IS '작성일';
COMMENT ON COLUMN ALIMNOTE.ALIM_CK IS '체크여부';

INSERT INTO ALIMNOTE VALUES(SEQ_ALIM.NEXTVAL,1,2020002,'안녕하세요^^ 민정이 오늘 열이 있어서 잠을 설쳤어요~~','좋음','나쁨','미열','약간','6~8시간','보통','minzzang',DEFAULT,'N');
INSERT INTO ALIMNOTE VALUES(SEQ_ALIM.NEXTVAL,1,2020001,'달이맘이에요~~ 오늘 달이가 콧물이 좀 나는데 불편해 하네여 쉬는시간마다 코좀 닦아주셔요^^*','좋음','보통','미열','보통','4시간미만','보통','dalmom',DEFAULT,'N');
INSERT INTO ALIMNOTE VALUES(SEQ_ALIM.NEXTVAL,1,2020001,'"달이가 오늘은 감기 기운이 있어서 컨디션이 안좋아요"','나쁨','나쁨','미열','약간','8시간','보통','dalmom',2020/02/29,'N');



CREATE TABLE ALIMHOME(              -- 귀가 통지서
    ALHM_NO NUMBER PRIMARY KEY,     -- 통지서 번호
    AL_CODE NUMBER DEFAULT 2,       -- 알림장 구별번호
    CNO NUMBER,                -- 자녀 번호
    ALHM_WAYHOME VARCHAR2(20),      -- 귀가방법
    ALHM_TIME VARCHAR2(20),         -- 귀가시간
    ALHM_STAUTS VARCHAR2(20),       -- 보호자 관계
    ALHM_PHONE VARCHAR2(20),        -- 보호자 전화번호
    ALHM_STATUS2 VARCHAR2(20),      -- 비상연락망 관계
    ALHM_PHONE2 VARCHAR2(20),       -- 비상연락망 전화번호
    ALHM_WRITER VARCHAR2(50),       -- 작성자
    ALHM_DATE DATE DEFAULT SYSDATE,
    ALIM_CK VARCHAR2(10),			-- 알림체크
    CONSTRAINT ALHM_CNO FOREIGN KEY(CNO) REFERENCES CHILD(CHILD_CODE),
    CONSTRAINT ALHM_WRITER FOREIGN KEY(ALHM_WRITER) REFERENCES MEMBER(USERID),
    CONSTRAINT ALHM_CODE FOREIGN KEY(AL_CODE) REFERENCES ALIMCODE(ALIM_CODE)
);
COMMENT ON COLUMN ALIMHOME.ALHM_NO IS '글번호';
COMMENT ON COLUMN ALIMHOME.AL_CODE IS '알림코드';
COMMENT ON COLUMN ALIMHOME.CNO IS '원아번호';
COMMENT ON COLUMN ALIMHOME.ALHM_WAYHOME IS '귀가수단';
COMMENT ON COLUMN ALIMHOME.ALHM_TIME IS '귀가시간';
COMMENT ON COLUMN ALIMHOME.ALHM_STATUS IS '보호자(귀가자)';
COMMENT ON COLUMN ALIMHOME.ALHM_PHONE IS '귀가자연락처';
COMMENT ON COLUMN ALIMHOME.ALHM_STATUS2 IS '보호자';
COMMENT ON COLUMN ALIMHOME.ALHM_PHONE2 IS '보호자연락처';
COMMENT ON COLUMN ALIMHOME.ALHM_WRITER IS '작성자';
COMMENT ON COLUMN ALIMHOME.ALHM_DATE IS '작성일';
COMMENT ON COLUMN ALIMHOME.ALIM_CK IS '체크여부';

INSERT INTO ALIMHOME VALUES(SEQ_ALHM.NEXTVAL,2,2020001,'차량','오전','하원도우미','010947293533','할머니','01044839683','dalmom',2020/02/29,'N');
INSERT INTO ALIMHOME VALUES(SEQ_ALHM.NEXTVAL,2,2020002,'도보','오전','엄마','01035389853','아빠','01038892848','minzzang',2020/02/29,'N');
INSERT INTO ALIMHOME VALUES(SEQ_ALHM.NEXTVAL,2,2020004,'도보','오후','외할머니','01044044404','외할아버지','01055055505','dalmom',DEFAULT,'N');


CREATE TABLE ALIMMEDI(              -- 투약 통지서
    ALMD_NO NUMBER PRIMARY KEY,     -- 투약 통지서 번호
    AL_CODE NUMBER DEFAULT 3,       -- 알림장 구별번호
    CNO NUMBER,                -- 자녀 번호
    ALMD_CON VARCHAR2(30),          -- 증상
    ALMD_TYPE VARCHAR2(30),         -- 약의 종류
    ALMD_VOL VARCHAR2(30),          -- 투약 용량
    ALMD_NUM VARCHAR2(30),          -- 투약 횟수
    ALMD_TIME VARCHAR2(30),         -- 투약 시간
    ALMD_TEMP VARCHAR2(30),         -- 보관 방법
    ALMD_PS VARCHAR2(100),          -- 특이사항
    ALMD_WRITER VARCHAR2(50),       -- 작성자
    ALMD_DATE DATE DEFAULT SYSDATE,
    ALIM_CK VARCHAR2(10),			-- 알림체크
    CONSTRAINT ALMD_CNO FOREIGN KEY(CNO) REFERENCES CHILD(CHILD_CODE),
    CONSTRAINT ALMD_WRITER FOREIGN KEY(ALMD_WRITER) REFERENCES MEMBER(USERID),
    CONSTRAINT ALMD_CODE FOREIGN KEY(AL_CODE) REFERENCES ALIMCODE(ALIM_CODE)
);
COMMENT ON COLUMN ALIMMEDI.ALMD_NO IS '글번호';
COMMENT ON COLUMN ALIMMEDI.AL_CODE IS '알림코드';
COMMENT ON COLUMN ALIMMEDI.CNO IS '원아번호';
COMMENT ON COLUMN ALIMMEDI.ALMD_CON IS '증상';
COMMENT ON COLUMN ALIMMEDI.ALMD_TYPE IS '약종류';
COMMENT ON COLUMN ALIMMEDI.ALMD_VOL IS '투약용량';
COMMENT ON COLUMN ALIMMEDI.ALMD_NUM IS '투약횟수';
COMMENT ON COLUMN ALIMMEDI.ALMD_TIME IS '투약시간';
COMMENT ON COLUMN ALIMMEDI.ALMD_TEMP IS '보관방법';
COMMENT ON COLUMN ALIMMEDI.ALMD_PS IS '특이사항';
COMMENT ON COLUMN ALIMMEDI.ALMD_WRITER IS '작성자';
COMMENT ON COLUMN ALIMMEDI.ALMD_DATE IS '작성일';
COMMENT ON COLUMN ALIMMEDI.ALIM_CK IS '체크여부';

INSERT INTO ALIMMEDI VALUES(SEQ_ALMD.NEXTVAL,3,2020001,'감기','물약','한봉','2회','오전9시','on','약을 싫어해요','dalmom',2020/02/29,'N');
INSERT INTO ALIMMEDI VALUES(SEQ_ALMD.NEXTVAL,3,2020002,'몸살','물약','6ml','1회','오전9시','on','약먹고 물 부탁드려요','minzzang',2020/02/29,'N');

CREATE TABLE FCALENDAR(
    FCALMONTH VARCHAR2(40) PRIMARY KEY,
    FCALIMG VARCHAR2(50)
);

CREATE TABLE EDUCALENDAR(
    EDUDATE VARCHAR2(40) PRIMARY KEY,
    EDUIMG VARCHAR2(50)
);


CREATE SEQUENCE SEQ_BNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
-- 게시판 번호 시퀀스

CREATE SEQUENCE SEQ_GNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
-- 사진 게시판 시퀀스

CREATE SEQUENCE SEQ_QNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
-- 문의 시퀀스
  
CREATE SEQUENCE SEQ_MEMNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
-- 회원번호 시퀀스
  
CREATE SEQUENCE SEQ_ALIM
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
-- 알림장 시퀀스 1
  
CREATE SEQUENCE SEQ_ALHM
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
-- 알림장 시퀀스 2
CREATE SEQUENCE SEQ_ALMD
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
-- 알림장 시퀀스 3



