CREATE TABLE MEMBER(
    MNO NUMBER PRIMARY KEY,           --회원번호
    USERID VARCHAR2(50) NOT NULL UNIQUE, --회원 아이디
    USERPWD VARCHAR2(300) NOT NULL, -- 비밀번호
    USERNAME VARCHAR2(10) NOT NULL, -- 회원이름
    GENDER CHAR(1) CHECK (GENDER IN('M','F')),  --성별
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,     --이메일
    PHONE VARCHAR2(50) UNIQUE NOT NULL,     --전화번호
    ADDRESS VARCHAR2(300) NOT NULL,         --주소
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL,--등록일
    CHILD_CODE NUMBER,                      --자녀 번호
    MSTATUS VARCHAR2(1) DEFAULT 'Y' CHECK (MEMSTATUS IN('Y','N')), -- 회원상태 Y- 가입상태 N- 삭제상태
    CONSTRAINT CH_CODE FOREIGN KEY(CHILD_CODE) REFERENCES CHILD(CHILD_CODE)
);


DROP TABLE NOTICE;
DROP TABLE MEMBER;


CREATE TABLE BOARD(
    BNO NUMBER PRIMARY KEY,                     -- 게시판번호
    BTITLE VARCHAR2(300) NOT NULL,              -- 게시판제목
    BCONTENT VARCHAR2(3000) NOT NULL,           -- 게시판 내용
    BWRITER VARCHAR2(50),                       -- 게시판 작성자
    BCOUNT NUMBER,                              -- 조회수
    BDATE DATE DEFAULT SYSDATE,                 -- 작성날짜
    BTIME VARCHAR2(50),                         -- (qna에서 날짜 선택, 보낼때 사용할예정)
    BTYPE NUMBER,                               -- 게시판 타입(사진게시판, 공지사항, qna)
    BFILE VARCHAR2(300),                         -- 첨부파일 or 사진
    BSTATUS VARCHAR2(1) DEFAULT 'Y' CHECK (BSTATUS IN('Y','N')),                       -- 게시글 삭제 상태(Y-삭제안됨 N-삭제됨)
    CONSTRAINT BO_WRITER FOREIGN KEY(BWRITER)REFERENCES MEMBER(USERID),
    CONSTRAINT BOARD_TYPE FOREIGN KEY(BTYPE) REFERENCES BOARDTYPE(BTYPE)
);

CREATE TABLE BOARDTYPE(
    BTYPE NUMBER PRIMARY KEY,
    BNAME VARCHAR2(20) NOT NULL UNIQUE
);


INSERT INTO BOARDTYPE VALUES(1,'공자사항');
INSERT INTO BOARDTYPE VALUES(2,'앨범');
INSERT INTO BOARDTYPE VALUES(3,'문의보내기');

  
CREATE SEQUENCE SEQ_BNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

  
CREATE SEQUENCE SEQ_MEMNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;




