CREATE SEQUENCE SEQ_ALIM
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_DRAFT
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_DAILY
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE JOB(
    JOB_CODE NUMBER PRIMARY KEY,
    JOB_NAME VARCHAR2(20) NOT NULL
);

INSERT INTO JOB VALUES(1,'¿øÀå');
INSERT INTO JOB VALUES(2,'ºÎ¿øÀå');
INSERT INTO JOB VALUES(3,'±³»ç');
INSERT INTO JOB VALUES(4,'¿µ¾ç»ç');
INSERT INTO JOB VALUES(5,'°è¾àÁ÷');

CREATE TABLE CLASS(
    CLASS_CODE NUMBER PRIMARY KEY,
    CLASS_NAME VARCHAR2(20) NOT NULL,
    LIMIT_AGE NUMBER NOT NULL,
    MAX_ENTRANCE NUMBER NOT NULL
);

--INSERT INTO CLASS VALUES(1,'¶±ÀÙ',2,20);
--INSERT INTO CLASS VALUES(2,'°¨ÀÙ',3,20);
--INSERT INTO CLASS VALUES(3,'±ÖÀÙ',5,20);
--INSERT INTO CLASS VALUES(4,'¹ãÀÙ',7,20);



CREATE TABLE EMPLOYEE(
    EMP_CODE NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(20) NOT NULL,
    EMP_JOB  NUMBER,
    EMP_NO VARCHAR2(50) NOT NULL UNIQUE,
    EMP_PHONE VARCHAR2(50) NOT NULL,
    EMP_ADDR VARCHAR2(150) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    ENT_DATE DATE,
    ENT_YN VARCHAR2(10) CHECK (ENT_YN IN('Y','N')),
    EMP_CLASS NUMBER,
    HOBONG NUMBER,
    CONSTRAINT FK_EMP_JOB FOREIGN KEY(EMP_JOB) REFERENCES JOB(JOB_CODE),
    CONSTRAINT FK_EMP_CLASS FOREIGN KEY(EMP_CLASS) REFERENCES CLASS(CLASS_CODE)
);    


CREATE TABLE DRAFT(
    DRAFT_NO NUMBER PRIMARY KEY,
    DRAFT_TYPE NUMBER NOT NULL,
    DRAFT_EMP NUMBER,
    DRAFT_DATE DATE NOT NULL,
    DRAFT_YN VARCHAR2(10) CHECK (DRAFT_YN IN('Y','N')),
    SIGN_EMP NUMBER,
    SIGN_YN VARCHAR2(10) CHECK (SIGN_YN IN('Y','N')),
    RETURN_REASON VARCHAR2(50),
    DRAFT_TITLE VARCHAR2(50) NOT NULL,
    DRAFT_CONTENT VARCHAR2(300) NOT NULL,
    DRAFT_FILE VARCHAR2(300),
    DRAFT_PROCESS VARCHAR2(20) CHECK (DRAFT_PROCESS IN('°ËÅä','¿Ï·á','¹Ý·Á')),
    CONSTRAINT FK_DRAFT_EMP FOREIGN KEY(DRAFT_EMP) REFERENCES EMPLOYEE(EMP_CODE),
    CONSTRAINT FK_SIGN_EMP FOREIGN KEY(SIGN_EMP) REFERENCES EMPLOYEE(EMP_CODE)
);   

CREATE TABLE DAILY(
    DAILY_NO NUMBER PRIMARY KEY,
    DAILY_CLASS NUMBER,
    DAILY_TITLE VARCHAR2(50) NOT NULL,
    DAILY_DATE DATE,
    DAILY_EMP_NAME VARCHAR2(20) NOT NULL,
    DAILY_PASS VARCHAR2(50),
    DAILY_FILE VARCHAR2(150),
    DAILY_EMP NUMBER,
    IS_DELETE VARCHAR2(10) CHECK(IS_DELETE IN ('Y','N')),
    CONSTRAINT FK_DAILY_EMP FOREIGN KEY(DAILY_EMP) REFERENCES EMPLOYEE(EMP_CODE),
    CONSTRAINT FK_DAILY_CLASS FOREIGN KEY(DAILY_CLASS) REFERENCES CLASS(CLASS_CODE)
);


CREATE TABLE CHILD(
    CHILD_CODE NUMBER PRIMARY KEY,
    CHILD_NAME VARCHAR2(20) NOT NULL,
    CHILD_GENDER VARCHAR2(10) CHECK (CHILD_GENDER IN('M','F')),
    CHILD_NO VARCHAR2(50) NOT NULL UNIQUE,
    CHILD_BIRTH DATE,
    CHILD_SUN_MOON VARCHAR2(20) CHECK(CHILD_SUN_MOON IN('¾ç·Â','À½·Â')),
    CHILD_ENRANCE DATE,
    CHILD_GRADUATE DATE,
    CHILD_ADDR VARCHAR2(150) NOT NULL,
    CHILD_IMAGE VARCHAR2(200),
    CHILD_AGE NUMBER,
    CHILD_IS_IN VARCHAR2(20) CHECK (CHILD_IS_IN IN('ÀçÇÐ','ÈÞ¿ø','Á¹¾÷')),
    CHILD_CLASS NUMBER,
    CONSTRAINT FK_CHILD_CLASS FOREIGN KEY(CHILD_CLASS) REFERENCES CLASS(CLASS_CODE)
);

CREATE TABLE FAMILY(
    CHILD_CODE NUMBER REFERENCES CHILD(CHILD_CODE),
    FAMILY_REL VARCHAR2(10) CHECK (FAMILY_REL IN('ºÎ','¸ð','±âÅ¸')),
    FAMILY_NAME VARCHAR2(20) NOT NULL,
    FAMILY_PHONE VARCHAR2(50),
    FAMILY_SUB VARCHAR2(50),
    FAMILY_EMAIL VARCHAR2(50),
    SIGN_YN VARCHAR2(10) CHECK (SIGN_YN IN ('Y','N')),
    FAMILY_MEMO VARCHAR2(50)
);




